// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjC11b_mDDyY35KbArgVVmmgazkdAZ4Aw',
    appId: '1:162367294326:web:38b76693fc688a62954857',
    messagingSenderId: '162367294326',
    projectId: 'todoapp-97032',
    authDomain: 'todoapp-97032.firebaseapp.com',
    storageBucket: 'todoapp-97032.appspot.com',
    measurementId: 'G-J18ZB4RP8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0wYqjrhTTw_s4KQEMa-XKL5XEQKvqMTk',
    appId: '1:162367294326:android:a33c3f0111a543b0954857',
    messagingSenderId: '162367294326',
    projectId: 'todoapp-97032',
    storageBucket: 'todoapp-97032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR2J0e30phskxx7X4isFOXWaq_jZXY0ws',
    appId: '1:162367294326:ios:5d1d44e4af94b46d954857',
    messagingSenderId: '162367294326',
    projectId: 'todoapp-97032',
    storageBucket: 'todoapp-97032.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR2J0e30phskxx7X4isFOXWaq_jZXY0ws',
    appId: '1:162367294326:ios:e60e7983d991668b954857',
    messagingSenderId: '162367294326',
    projectId: 'todoapp-97032',
    storageBucket: 'todoapp-97032.appspot.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
